apiVersion: apps/v1                 
kind:  Deployment                  
metadata:                          
    name: ip-app-deployment          
spec:                                
    replicas: 3                        
    selector:                  
        matchLabels:            
            app: ip-app-label   
    template:                   
        metadata:               
            labels:
                app: ip-app-label
        spec:               
            containers:
            - name: ip-app-container
              image: harshajain/ip_app:2
              imagePullPolicy: Always
              ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ip-app-service
spec:
    type: ClusterIP
    selector:
        app: ip-app-label
    ports:
      - name: http
        port: 80
        targetPort: 80
